#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ZTNET_URL="${GSE_ZTNET_URL:-http://localhost:3002}"

if [[ $EUID -eq 0 ]]; then
  QUADLET_DIR="/etc/containers/systemd"
  SYSTEMCTL="systemctl"
else
  QUADLET_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/containers/systemd"
  SYSTEMCTL="systemctl --user"
fi

CREDENTIALS_FILE="${QUADLET_DIR}/ztnet-credentials.env"

echo "==> 1. Waiting for ZTNET to become responsive on ${ZTNET_URL}..."
MAX_TRIES=30
COUNT=0
until curl -sI "${ZTNET_URL}/" >/dev/null 2>&1 || [[ $COUNT -eq $MAX_TRIES ]]; do
  sleep 2
  COUNT=$((COUNT + 1))
  echo "    Waiting for ZTNET... ($COUNT/$MAX_TRIES)"
done

if [[ $COUNT -eq $MAX_TRIES ]]; then
  echo "Error: ZTNET failed to respond within 60 seconds on ${ZTNET_URL}." >&2
  echo "Check logs with: ${SYSTEMCTL} status drop-ztnet.service" >&2
  exit 1
fi

echo "==> 2. Running ZTNET bootstrap (admin user, organization, API token)..."
OUTPUT=$(GSE_ZTNET_URL="${ZTNET_URL}" node "${SCRIPT_DIR}/ztnet-bootstrap.mjs")
echo "${OUTPUT}"

ORG_ID=$(echo "${OUTPUT}" | grep "GSE_ZTNET_ORG=" | cut -d'=' -f2)
API_TOKEN=$(echo "${OUTPUT}" | grep "GSE_ZTNET_TOKEN=" | cut -d'=' -f2)

if [[ -z "${ORG_ID}" || -z "${API_TOKEN}" ]]; then
  echo "Error: Failed to parse organization ID or API token from bootstrap output." >&2
  exit 1
fi

echo "==> 3. Writing credentials to ${CREDENTIALS_FILE}..."
cat << EOF > "${CREDENTIALS_FILE}"
# GSE multiplayer mesh network credentials
# Generated by ./bootstrap-ztnet.sh
GSE_MESH_BACKEND=ztnet
GSE_ZTNET_URL=http://172.20.0.32:3000
GSE_ZTNET_ORG=${ORG_ID}
GSE_ZTNET_TOKEN=${API_TOKEN}
EOF

echo "==> 4. Restarting Drop service to connect to ZTNET..."
${SYSTEMCTL} restart drop.service

echo ""
echo "==============================================================="
echo " ZTNET Mesh successfully configured for Drop!"
echo " GSE Organization ID: ${ORG_ID}"
echo " Check Drop logs:     ${SYSTEMCTL} status drop.service"
echo "==============================================================="
